# Generated by Django 4.2.1 on 2023-05-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.IntegerField()),
                ('StuName', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('GPA', models.IntegerField()),
                ('Gender', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('Status', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Mobile', models.IntegerField()),
                ('Nationality', models.CharField(max_length=255)),
                ('NationalityID', models.IntegerField(null=True)),
            ],
        ),
    ]
