# Generated by Django 4.2.1 on 2023-06-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_adminsdata_delete_admindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_student',
            name='DOB',
            field=models.CharField(max_length=255),
        ),
    ]
