# Generated by Django 2.1.15 on 2023-06-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20230601_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('memid', models.IntegerField()),
                ('section', models.CharField(max_length=255)),
            ],
        ),
    ]
