# Generated by Django 2.1.15 on 2023-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_teamdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='section',
            field=models.IntegerField(),
        ),
    ]
